import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as lucide from "@ng-icons/lucide";

// Emit only referenced icons. CSS masks also support icon names supplied by table metadata.
const names = new Set();
function scan(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) scan(path);
    else if (/\.(html|ts|scss)$/.test(path)) {
      for (const match of readFileSync(path, "utf8").matchAll(
        /\bicon-([a-z-]+)/g,
      )) {
        const name = match[1];
        const exportName = `lucide${name
          .split("-")
          .map((word) => word[0].toUpperCase() + word.slice(1))
          .join("")}`;
        if (lucide[exportName]) names.add(name);
      }
    }
  }
}
scan("src/app");
let css = `/* Lucide icons from @ng-icons/lucide, ISC licensed. Generated by scripts/update-icons.mjs. */
.icon { display:inline-block; width:1em; height:1em; flex-shrink:0; vertical-align:-.125em; background-color:currentColor; mask:var(--app-icon) center / contain no-repeat; }
.icon-spin { animation:icon-spin 1s linear infinite; }
@keyframes icon-spin { to { transform:rotate(360deg); } }
`;
for (const name of [...names].sort()) {
  const exportName = `lucide${name
    .split("-")
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join("")}`;
  const svg = lucide[exportName].replace(/style="[^"]*"/, 'stroke-width="2"');
  css += `.icon-${name} { --app-icon: url("data:image/svg+xml,${encodeURIComponent(svg).replace(/'/g, "%27")}"); }\n`;
}
writeFileSync("src/assets/icons.css", css);
